import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "secondary-fixed": "#ffdbcd",
        "inverse-surface": "#2f312e",
        "on-tertiary-fixed": "#161e00",
        "on-surface": "#1a1c19",
        "on-primary-fixed-variant": "#3c475d",
        "on-secondary-fixed": "#360f00",
        "surface-container-low": "#f4f4ef",
        "on-tertiary": "#ffffff",
        "primary-container": "#1b263b",
        "error": "#ba1a1a",
        "on-secondary": "#ffffff",
        "tertiary-fixed-dim": "#bbcf7c",
        "inverse-on-surface": "#f1f1ec",
        "surface-container": "#eeeee9",
        "inverse-primary": "#bbc6e2",
        "secondary-container": "#fe9e72",
        "error-container": "#ffdad6",
        "surface-dim": "#dadad5",
        "surface-bright": "#fafaf5",
        "outline": "#75777d",
        "on-tertiary-container": "#829549",
        "primary-fixed": "#d7e2ff",
        "tertiary": "#0e1400",
        "surface": "#fafaf5",
        "on-error-container": "#93000a",
        "outline-variant": "#c5c6cd",
        "surface-tint": "#545e76",
        "tertiary-container": "#202a00",
        "on-secondary-fixed-variant": "#76320f",
        "primary": "#051125",
        "on-background": "#1a1c19",
        "surface-container-high": "#e8e8e3",
        "on-error": "#ffffff",
        "on-secondary-container": "#773310",
        "primary-fixed-dim": "#bbc6e2",
        "secondary-fixed-dim": "#ffb596",
        "tertiary-fixed": "#d7ec95",
        "surface-container-highest": "#e3e3de",
        "on-tertiary-fixed-variant": "#3d4c05",
        "secondary": "#944925",
        "background": "#fafaf5",
        "on-primary-container": "#828da7",
        "on-primary": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "on-surface-variant": "#45474d",
        "surface-variant": "#e3e3de",
        "on-primary-fixed": "#101b30"
      },
      fontFamily: {
        headline: ['var(--font-newsreader)', 'serif'],
        body: ['var(--font-manrope)', 'sans-serif'],
        label: ['var(--font-manrope)', 'sans-serif'],
      }
    },
  },
  plugins: [],
};
export default config;
